---
# This playbook install a hosts file for all the hosts

#TODO Remove in future versions
- name: remove vagrant-hostmanager entries
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    state: absent
    marker: "## {mark}"
    marker_begin: "vagrant-hostmanager-start"
    marker_end: "vagrant-hostmanager-end"
  become: yes
  become_user: root

- name: Check if hosts file exists
  stat:
    path: "{{ playbook_dir }}/../config/hosts.txt"
  register: hosts_file_stat

- name: Load hosts entries from file
  set_fact:
    splunk_hosts_entries: "{{ lookup('file', hosts_file_stat.stat.path) }}"
  when: 
    - splunk_hosts_entries is not defined or not splunk_hosts_entries
    - hosts_file_stat.stat.exists

- name: add splunk hosts to /etc/hosts
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ splunk_hosts_entries | default('', true) }}
    marker: "# {mark} SPLUNKENIZER MANAGED BLOCK (splunk hosts)"
  become: yes
  become_user: root
  when: splunk_hosts_entries is defined and splunk_hosts_entries
